### ISSUE TITLE
podOptions probes ignored

### ISSUE THREAD

**Issue by makuk66** [apache/lucene-solr-operator#208]
I tried setting solrcloud values:

```
podOptions:
  livenessProbe:
    tcpSocket:
      port: 8983
    initialDelaySeconds: 5
    periodSeconds: 5
  readinessProbe:
    tcpSocket:
      port: 8983
    initialDelaySeconds: 5
    periodSeconds: 5

```

but these settings seemed to be ignored; the normal `http-get` probes were used
