### ISSUE TITLE
Solr cloud never getes deleted when reclaimPolicy is set to Delete

### ISSUE THREAD

**Issue by krishnachalla-hv** [apache/lucene-solr-operator#212]
I facing this issue after upgrading to **v0.2.8**. Earlier I was using **v0.2.6** version of solrcloud things were working fine as expected except the **pvc** deletion that were created by solrcloud since the feature was not available in **v0.2.6**. Now I am testing my application with latest version of solr-operator(v02.8) facing wired issue, When I set the **reclaimPolicy: Delete** for solr as well provided Zookeeper instance in **solrcloud** yaml file, when I tried to uninstall it only the solr-operator and zk-operatorr are getting uninstalled but the solrcloud and zookeepr pods never gets terminated. I created one sample test chart  like below tested these things but the issue is still the same.

```
apiVersion: v2
name: test
description: A Helm chart for intializing multi node solr cloud.
type: application
version: 1.0.0
appVersion: 1.0.0
dependencies:
  - name: solr-operator
    version: 0.2.8
    repository: "https://apache.github.io/lucene-solr-operator/charts"
    condition: solr-operator.enabled

  - name: zookeeper-operator
    version: 0.3.0
    repository: "https://kubernetes-charts.banzaicloud.com"
    condition: zookeeper-operator.enabled
```
    
And my solr cloud yaml configuration is:
```
apiVersion: solr.bloomberg.com/v1beta1
kind: SolrCloud
metadata:
  name: {{ .Release.Name }}
spec:
  dataStorage:
    persistent:
      reclaimPolicy: Delete
      pvcTemplate:
        spec:
          resources:
            requests:
              storage: "5Gi"
  replicas: 2
  solrImage:
    tag: 8.7.0
  solrJavaMem: "-Xms1g -Xmx3g"
  customSolrKubeOptions:
    podOptions:
      resources:
        limits:
          memory: "1G"
        requests:
          cpu: "65m"
          memory: "156Mi"
  zookeeperRef:
    provided:
      chroot: "/solr"
      persistence:
        reclaimPolicy: Delete
        spec:
          resources:
            requests:
              storage: "5Gi"
      replicas: 3
      zookeeperPodPolicy:
        resources:
          limits:
            memory: "1G"
          requests:
            cpu: "65m"
            memory: "156Mi"
  solrOpts: "-Dsolr.autoSoftCommit.maxTime=10000"
  solrGCTune: "-XX:SurvivorRatio=4 -XX:TargetSurvivorRatio=90 -XX:MaxTenuringThreshold=8"
```
  
  If I set the **reclaimPolicy** to **Retain** and uninstall the chart, solrcloud is also uninstalling properly.
