### ISSUE TITLE
Our client needs zookeeper hosts

### ISSUE THREAD

**Issue by khauser** [apache/lucene-solr-operator#233]
Hi,

in our current software we use the client library "solr-solrj" to connect to our solr/zookeeper installation (on virtual machines).

build.gradle
```
implementation("org.apache.solr:solr-solrj:8.4.1")
```

In code we are then able to connect to solr by adding a list of valid zookeeper hosts.
```
import org.apache.solr.client.solrj.impl.CloudSolrClient
...
var zkHosts: List<String> = mutableListOf("localhost:8983")
var path: Optional<String> = Optional.empty() //Optional.of("/solr")

val client = CloudSolrClient.Builder(zkHosts, path).build()
```
As far as we understood is that a zookeeper instance is called to return a valid solr instance with which our application can work internally.

We now have moved our solr/zookeeper installation into kubernetes using this operator and now fail to connect our software with it from outsite the cluster. We only see that the solr-service is exposable via LB or Ingress but no zookeeper.

What are your recommentations to proceed here? Switch to another client library or change the way we use it? Could the zookeepers be exposed and be configured to return the exposed solr instances?

Thanks for help
Karsten

**Comment by khauser** [comment]
We now added an additional LB in front of the zookeeper instances in Azure with a private IP:
```
apiVersion: v1
kind: Service
metadata:
  name: solr-zookeeper-internal-lb
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
  - port: 2181
  selector:
    app: solr-cloud-solrcloud-zookeeper
```

Together with the SolrClound+Ingress definition:
```
apiVersion: solr.bloomberg.com/v1beta1
kind: SolrCloud
metadata:
  name: perftest-solr-cloud
spec:
  replicas: 3
  solrImage:
    tag: 8.7.0
  solrJavaMem: "-Xms300m -Xmx300m"
  solrAddressability:
    external:
      method: Ingress
      useExternalAddress: true
      domainName: "<our_domain>"
```
it seems to work properly.

Thanks for your great work!
